### PR TITLE
my improvements for sm64dse

### PR DESCRIPTION
**Pull request by jupahe64**
This is something i have worked on for a while. It's sm64dse 2.3.5 with some 

Changes:
-a better ObjectRenderer for: 
    Paintings(they are rotated properly),
    Exits(they show their exact rotation, width and height)
    InvisiblePole(showing the actual height),
    StarMarkers(you now can see if it is for red coins or something else)
-the highlight of a path now also shows the connections between the nodes,
Bugfixes:
-scrolling an object works again
-if you set an object to be on another layer, all involved layers will update, so it doesn't crash if 
 you reselect the object thats already unloaded from the objectlist
New Features:
-copy and paste coordinates buttons
-a new alternate interface for editing the LevelObjects Properties,
-in the 3d model tab it's possible now to select the different areas of the level to show up
-the view will zoom to an object if you doubleClick it in the object list

I would like, if this could be an official update for sm64dse.

btw. all these files are copied from my own project: https://github.com/jupahe64/my-improved-version-of-sm64dse
i just now realised that it would be better to do it as a pull request

### CODE REVIEW

**Comment by Fiachra1993** [comment]
Thanks for the pull request however I can't review it in its current state due to the line endings of over 200 files having been changed. Could you try the following: 
- Take a new branch off yours
- Configure core.autocrlf to be true
- Refresh the repository as described here: https://help.github.com/articles/dealing-with-line-endings/
- Commit your changes and open a new pull request

In the meantime I can test your changes out.

**Comment by Fiachra1993** [comment]
These are good features especially the exit rendering and the parameter settings for exits, views etc. Well done for working out what "Type 14" objects are for.

A few suggestions/issues: 
- Selecting an exit object and then selecting the table property view causes the editor to crash
- Ensure proper text on any labels, descriptions etc. e.g. "CopyCoordinates" -> "Copy Co-ordinates"
- Ensure no overlapping UI controls e.g. the view object parameters 2 and 3 are cut off a bit at the top and the box for parameter 3 overlaps the lower control border
- For the raw parameters in the "New" interface, pad the values with zeros so "000F" instead of "F" for example

If you need help fixing the line endings issue let me know and I can try it myself.

**Comment by jupahe64** [comment]
Alright, i think i fixed almost all issues you told me, i made a completely new control/widget to make raw editing a lot easier, also polished the design of the "New interface" and btw. got rid of the "Old" one, as in my opinion its no longer needed. Also i extended the star marker/ power star-Render to show all known types with accurate models. And i implemented an easy way to set up paintings, stars and star markers in the new interface. Btw. i figured out that the painting actually contains 5 parameters, one of them being the type/mode/wobble/appearance. Also found a better way to organize path and fixed the bug that saved them in the wrong order. And there is now an auto file filtering for BMDs, BCAs, KLCs, BTPs and all 2d formats, which will avoid that someone accidentally selects the wrong file type.
These are the mayor changes i made in the meantime, i hope you like them.

**Comment by jupahe64** [comment]
And is there a better way to communicate? Cause i may have some questions during development.

**Comment by awiebe** [comment]
NB There are also a bunch of .DS_Store you should add to your global gitignore.

**Comment by Fiachra1993** [comment]
Thanks, I'll take a look over the weekend.

**Comment by Fiachra1993** [comment]
Can you please merge the latest changes from my master branch into your (or just add a .gitattributes file to your repository with the following content: https://github.com/StapleButter/SM64DSe/blob/master/.gitattributes)

I have some minor changes I'd like to make. If you add that .gitattributes to your repository: 
- I'll open a pull request for my changes into yours 
- You (review and) merge my PR
- You then open a PR from your repo. into mine which would include the changes I've made and won't include changes to line endings.

Good work.

If you have questions you can e-mail me: Fiachra93@yandex.com

**Comment by jupahe64** [comment]
Alright i added the gitattributes

**Comment by Fiachra1993** [comment]
As discussed: https://github.com/jupahe64/SM64DSe/pull/1

**Comment by Fiachra1993** [comment]
Merged in latest commit: don't know best way to make changes on top of a github PR like this. Have updated list of contributers.

**Pull request closed without merging**
